version: '3'

# Instruções de execução e definição de caracteristicas para os serviçõs/containers.

services:
  db:
    build: ./db
    #command: python3 manage.py runserver
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sistema
    ports:
      - "3366:3306"
    #para conectar usar o ip 172.18.0.3:3366 IPAdress:PortaLocal
    networks:
      - projectWeb
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1080M 


  web:
    depends_on:
      - db
    build: .\
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    networks:
     - projectWeb
    #volumes:
    #  - "C:\\Users\\arthursouza\\Repositorios\\IaArtGenerator\\docker:/app"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 560M
    volumes:
      - .:/apps
    links:
      - db

# Definição de rede docker para comunicação de containers.
networks:
  projectWeb:
    driver: bridge
    ipam:
     config:
       - subnet: 127.0.0.0/8
         gateway: 127.0.0.1
    
  
