version: '3.7'

services:
  #db:
   # build: ./mysql/
    #restart: always
    #env_file:
    #  - ./config/db.env
    #ports:
    #  - "3306:3306"
    #networks:
    #  - projectumcompose

  web:
    #depends_on:
    #  - db
    build: ./app
    ports:
      - "8080:8080"
    restart: always
    networks:
      - projectumcompose
    volumes:
      - "C:\\Users\\arthursouza\\Repositorios\\IaArtGenerator\\Docker\\app:/app"
networks:
  projectumcompose:
    
  
