version: '3.3'

services:
  #db:
   # build: ./mysql/
    #restart: always
    #env_file:
    #  - ./config/db.env
    #ports:
    #  - "3306:3306"
    #networks:
    #  - projectumcompose

  web:
    #depends_on:
    #  - db
    build: ./flask
    ports:
      - "80:5000"
    restart: always
    networks:
      - projectumcompose
    volumes:
      - "D:\\repos\\IaArtGenerator\\Docker\\flask:/app"

networks:
  projectumcompose:
    
  
